IMDB-BINARY:
  lr: 0.0006
  weight_decay: 3e-6
  num_layers: 2
  num_hidden: 1024
  max_epoch: 80
  mask_rate: 0.3
  in_drop: 0.3
  drop_p: 0.35
  activation: PReLU
  alpha: 1
  tau: 0.25
  residual: False
  norm: batchnorm
  use_scheduler: False
  pooling: mean
  batch_size: 8
IMDB-MULTI:
  lr: 3e-6
  weight_decay: 0.0004
  num_layers: 3
  num_hidden: 256
  max_epoch: 100
  mask_rate: 0.45
  in_drop: 0.25
  drop_p: 0.6
  activation: LeakyReLU
  alpha: 2
  tau: 0.35
  residual: False
  norm: layernorm
  use_scheduler: True
  pooling: mean
  batch_size: 32
PROTEINS:
  lr: 9e-5
  weight_decay: 4e-6
  num_layers: 2
  num_hidden: 256
  max_epoch: 380
  mask_rate: 0.3
  in_drop: 0.2
  drop_p: 0.45
  activation: ELU
  alpha: 1
  tau: 0.5
  residual: True
  norm: layernorm
  use_scheduler: True
  pooling: max
  batch_size: 32
COLLAB:
  lr: 0.0003
  weight_decay: 8e-6
  num_layers: 1
  num_hidden: 512
  max_epoch: 470
  mask_rate: 0.3
  in_drop: 0.25
  drop_p: 0.55
  activation: ELU
  alpha: 1
  tau: 0.15
  residual: True
  norm: layernorm
  use_scheduler: True
  pooling: mean
  batch_size: 8
MUTAG:
  lr: 7e-5
  weight_decay: 0.06
  num_layers: 4
  num_hidden: 1024
  max_epoch: 290
  mask_rate: 0.35
  in_drop: 0.1
  drop_p: 0.55
  activation: ReLU
  alpha: 3
  tau: 0.3
  residual: False
  norm: batchnorm
  use_scheduler: True
  pooling: mean
  batch_size: 16
REDDIT-BINARY:
  lr: 2e-5
  weight_decay: 0.001
  num_layers: 2
  num_hidden: 256
  max_epoch: 420
  mask_rate: 0.6
  in_drop: 0.1
  drop_p: 0.3
  activation: ReLU
  alpha: 1
  tau: 0.2
  residual: True
  norm: layernorm
  use_scheduler: False
  pooling: mean
  batch_size: 16
# REDDIT-BINARY:
#   lr: 0.003
#   weight_decay: 7e-5
#   num_layers: 2
#   num_hidden: 256
#   max_epoch: 230
#   mask_rate: 0.75
#   in_drop: 0.25
#   drop_p: 0.1
#   activation: ReLU
#   alpha: 1
#   tau: 0.25
#   residual: True
#   norm: layernorm
#   use_scheduler: False
#   pooling: sum
#   batch_size: 16
NCI1:
  lr: 7e-5
  weight_decay: 0.002
  num_layers: 4
  num_hidden: 1024
  max_epoch: 400
  mask_rate: 0.35
  in_drop: 0.1
  drop_p: 0.3
  activation: LeakyReLU
  alpha: 1
  tau: 0.1
  residual: True
  norm: layernorm
  use_scheduler: False
  pooling: sum
  batch_size: 8
