cora:
  lr: 0.0008
  weight_decay: 0.0001
  lr_f: 0.009
  weight_decay_f: 0.009
  num_heads: 2
  num_layers: 2 
  num_hidden: 256
  max_epoch: 1500
  max_epoch_f: 300
  mask_rate: 0.5
  in_drop: 0.5
  attn_drop: 0.4
  drop_p: 0.1 
  activation: GELU
  alpha: 1
  tau: 0.5
  residual: False
  norm: None
  use_scheduler: False
citeseer:
  lr: 0.003
  weight_decay: 0.0002
  lr_f: 0.08
  weight_decay_f: 0.08
  num_heads: 4
  num_layers: 1 
  num_hidden: 128
  max_epoch: 1500
  max_epoch_f: 500
  mask_rate: 0.5
  in_drop: 0.2
  attn_drop: 0.3
  drop_p: 0.55 
  activation: GELU
  alpha: 2
  tau: 0.55
  residual: True
  norm: None
  use_scheduler: False
pubmed:
  lr: 0.0004
  weight_decay: 7e-6
  lr_f: 7e-5
  weight_decay_f: 0.0004
  num_heads: 4
  num_layers: 2
  num_hidden: 256
  max_epoch: 2000
  max_epoch_f: 1500
  mask_rate: 0.65
  in_drop: 0.15
  attn_drop: 0.3
  drop_p: 0.15 
  activation: GELU
  alpha: 3
  tau: 0.8
  residual: False
  norm: layernorm
  use_scheduler: True
# pubmed:
#   lr: 0.001
#   weight_decay: 1e-5
#   lr_f: 0.003
#   weight_decay_f: 5e-6
#   num_heads: 2
#   num_layers: 2
#   num_hidden: 256
#   max_epoch: 1500
#   max_epoch_f: 400
#   mask_rate: 0.55
#   in_drop: 0.3
#   attn_drop: 0.5
#   drop_p: 0.45 
#   activation: PReLU
#   alpha: 3
#   tau: 0.55
#   residual: True
#   norm: None
#   use_scheduler: False
photo:
  lr: 0.001
  weight_decay: 0.03
  lr_f: 0.06
  weight_decay_f: 0.0007
  num_heads: 4
  num_layers: 2
  num_hidden: 1024
  max_epoch: 400
  max_epoch_f: 1000
  mask_rate: 0.4
  in_drop: 0.1
  attn_drop: 0.35
  drop_p: 0.6 
  activation: ReLU
  alpha: 1
  tau: 0.1
  residual: True
  norm: layernorm
  use_scheduler: True
computer:
  lr: 0.002
  weight_decay: 0.0009
  lr_f: 0.03
  weight_decay_f: 0.0001
  num_heads: 2
  num_layers: 2
  num_hidden: 512
  max_epoch: 1000
  max_epoch_f: 1000
  mask_rate: 0.45
  in_drop: 0.3
  attn_drop: 0.4
  drop_p: 0.55
  activation: PReLU
  alpha: 3
  tau: 0.85
  residual: True
  norm: layernorm
  use_scheduler: True
